<?php

namespace AppBundle\Repository;

/**
 * DicoTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DicoTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
