<?php

namespace AppBundle\Repository;

/**
 * DicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DicoRepository extends \Doctrine\ORM\EntityRepository
{
}
